import unittest

from .. import common


class CommonTest(unittest.TestCase):

    def test_update_string_by_stringindexes(self):

        long_content = '##  Harici Bağlantılar\n\n- [2019 Calculus 1 ~ Muhammet Esat Büyükbulut](http://muhammetesatbuyukbulut.com/category/dersler/calc-1/)\n\n<!-- Autogenerated with YPackage Integration tool -->\n\n- [2018 Tam Calculus ~ Asma Mirkhan.pdf](2018%20Tam%20Calculus%20~%20Asma%20Mirkhan.pdf)\n\n<!-- Autogenerated with YPackage Integration tool -->\n'

        long_sindex = '\n<!-- Autogenerated with YPackage Integration tool -->\n\n'
        long_eindex = '\n\n<!-- Autogenerated with YPackage Integration tool -->\n'

        long_result = '##  Harici Bağlantılar\n\n- [2019 Calculus 1 ~ Muhammet Esat Büyükbulut](http://muhammetesatbuyukbulut.com/category/dersler/calc-1/)\n\n<!-- Autogenerated with YPackage Integration tool -->\n\nYPackage\n\n<!-- Autogenerated with YPackage Integration tool -->\n'

        result = common.update_string_by_stringindexes(
            'YPackage',
            long_content,
            long_sindex,
            long_eindex
        )

        self.assertEqual(result, long_result)
